### ISSUE TITLE
SSL error on app launch

### ISSUE THREAD

**Issue by rkunal** [KrauseFx/FxLifeSheet#123]
I have attempted to install on 3 devices ( vps linux, local windows and directly on heroku ). Each time, there is error around SSL. 
Error logs are shared at the end.

1. I did setup all env variables to best of my knowledge. 
2. Telegram user id and telegram chat id were same.
3. I did not execute create-table queries on heroku. But on local/vps DBs, I did.
4. Its free plan on heroku, first time user.

How can I fix this and launch app ? 
Thank you.

_Dev Machines  ( npm run dev )_
```
12:16:41 AM worker.1 |  Successfully connected to Postgres
Launching up Telegram bot...
12:16:41 AM worker.1 |  Error: self-signed certificate
12:16:41 AM worker.1 |      at TLSSocket.onConnectSecure (node:_tls_wrap:1531:34)
12:16:41 AM worker.1 |      at TLSSocket.emit (node:events:527:28)
12:16:41 AM worker.1 |      at TLSSocket._finishInit (node:_tls_wrap:945:8)
12:16:41 AM worker.1 |      at ssl.onhandshakedone (node:_tls_wrap:726:12) {
12:16:41 AM worker.1 |    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
12:16:41 AM worker.1 |  }
 undefined
12:16:41 AM worker.1 |  Error: Connection terminated unexpectedly
12:16:41 AM worker.1 |      at Connection.<anonymous> (C:\.....\FxLifeSheet\node_modules\pg\lib\client.js:132:73)
12:16:41 AM worker.1 |      at Object.onceWrapper (node:events:641:28)
12:16:41 AM worker.1 |      at Connection.emit (node:events:527:28)
12:16:41 AM worker.1 |      at Socket.<anonymous> (C:\......\FxLifeSheet\node_modules\pg\lib\connection.js:57:12)
12:16:41 AM worker.1 |      at Socket.emit (node:events:539:35)
12:16:41 AM worker.1 |      at TCP.<anonymous> (node:net:715:12) 
undefined
12:16:41 AM web.1   |  Error: self-signed certificate
12:16:41 AM web.1   |      at TLSSocket.onConnectSecure (node:_tls_wrap:1531:34)
12:16:41 AM web.1   |      at TLSSocket.emit (node:events:527:28)
12:16:41 AM web.1   |      at TLSSocket._finishInit (node:_tls_wrap:945:8)
12:16:41 AM web.1   |      at ssl.onhandshakedone (node:_tls_wrap:726:12) {
12:16:41 AM web.1   |    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
12:16:41 AM web.1   |  }
12:16:41 AM web.1   |  undefined
12:16:41 AM web.1   |  Error: Connection terminated unexpectedly
12:16:41 AM web.1   |      at Connection.<anonymous> ..............................

```

```
$ heroku logs --tail
 »   Warning: heroku update available from 7.53.0 to 7.60.2.
2022-05-07T18:45:05.526410+00:00 app[web.1]: at TCP.<anonymous> (node:net:709:12)
2022-05-07T18:45:05.526454+00:00 app[web.1]: undefined
2022-05-07T18:45:05.526517+00:00 app[web.1]: Error: Connection terminated unexpectedly
2022-05-07T18:45:05.526517+00:00 app[web.1]: at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
2022-05-07T18:45:05.526518+00:00 app[web.1]: at Object.onceWrapper (node:events:641:28)
2022-05-07T18:45:05.526518+00:00 app[web.1]: at Connection.emit (node:events:527:28)
2022-05-07T18:45:05.526518+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:57:12)
2022-05-07T18:45:05.526519+00:00 app[web.1]: at Socket.emit (node:events:539:35)
2022-05-07T18:45:05.526519+00:00 app[web.1]: at TCP.<anonymous> (node:net:709:12)
2022-05-07T18:45:05.526553+00:00 app[web.1]: undefined
2022-05-07T18:45:05.526614+00:00 app[web.1]: Error: Connection terminated unexpectedly
2022-05-07T18:45:05.526615+00:00 app[web.1]: at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
2022-05-07T18:45:05.526615+00:00 app[web.1]: at Object.onceWrapper (node:events:641:28)
2022-05-07T18:45:05.526615+00:00 app[web.1]: at Connection.emit (node:events:527:28)
2022-05-07T18:45:05.526616+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:57:12)

.........................

2022-05-07T18:45:05.529929+00:00 app[web.1]: /app/web.js:137
2022-05-07T18:45:05.529930+00:00 app[web.1]: value: Number(res.rows[0].value)
2022-05-07T18:45:05.529931+00:00 app[web.1]: ^
2022-05-07T18:45:05.529931+00:00 app[web.1]:
2022-05-07T18:45:05.529931+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'rows')
2022-05-07T18:45:05.529932+00:00 app[web.1]: at Query.callback (/app/web.js:137:27)
2022-05-07T18:45:05.529932+00:00 app[web.1]: at Query.handleError (/app/node_modules/pg/lib/query.js:128:19)
2022-05-07T18:45:05.529933+00:00 app[web.1]: at /app/node_modules/pg/lib/client.js:75:15
2022-05-07T18:45:05.529933+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:78:11)
2022-05-07T18:45:05.693004+00:00 heroku[web.1]: Process exited with status 1
2022-05-07T18:45:05.862351+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-07T19:05:10.977202+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=xxxxxxxxxxxxxxx request_id=xxxxxx fwd=xxxxx  dyno= connect= service= status=503 bytes= protocol=https

```

**Comment by rkunal** [comment]
1. App requires a valid SSL. Paid heroku instance should provide it. Or you may add appropriate config for local machines
2. Database creation is needed
I could not get a working installation. But closing this issue as per above resolutions.
